apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: my-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: my-app
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: app
          image: ahmedelheity/instabug:1.0  # Replace with your actual image name and tag
          ports:
            - containerPort: 9090
          env:
            - name: MYSQL_HOST
              value: "4.246.151.92"
            - name: MYSQL_USER
              value: "instabug"
            - name: MYSQL_PASS
              value: "instabug"
            - name: MYSQL_PORT
              value: "3306"
          envFrom:
            - configMapRef:
                name: app-config
          imagePullPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_ROOT_PASSWORD: example
  MYSQL_DATABASE: internship
  MYSQL_USER: instabug
  MYSQL_PASSWORD: instabug

---

apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: my-db
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: my-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
        - name: db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_DATABASE
              value: internship
            - name: MYSQL_USER
              value: instabug
            - name: MYSQL_PASSWORD
              value: instabug
          imagePullPolicy: IfNotPresent
