apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: my-db
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: my-db